-- ===========================================================================
-- Clemmy Schools — production schema migration
--
-- Generated by diffing the live production schema (clemmyschools_schoolV12,
-- MariaDB 10.5.29, 179 tables) against local dev (schoolvault-4-jul-26,
-- MariaDB 10.4.28, 192 tables) on 2026-07-26. Every statement below comes
-- from that diff; nothing is written from memory.
--
-- Contents:  14 new tables, 32 new columns.
--
-- Safe to re-run: every statement uses IF NOT EXISTS. All added columns are
-- either nullable or carry a DEFAULT, so existing rows are never rewritten
-- and no data is touched. No foreign keys, so statement order is irrelevant.
--
-- Verified: applying this to a copy of the production schema makes it match
-- local exactly (0 remaining table or column differences).
--
-- Apply:  mysql -u USER -p DBNAME < clemmy_production_migration.sql
-- Order:  staging first, then production after staging tests pass.
-- ===========================================================================


-- ---------------------------------------------------------------------------
-- SECTION 1 — Tables absent from production (14)
-- ---------------------------------------------------------------------------

CREATE TABLE IF NOT EXISTS `affective_domain_type` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `branch_id` int(11) NOT NULL,
  `sort_order` tinyint(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_adt_branch` (`branch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
CREATE TABLE IF NOT EXISTS `psychomotor_domain_type` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) NOT NULL,
  `branch_id` int(11) NOT NULL,
  `sort_order` tinyint(4) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  KEY `idx_pdt_branch` (`branch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
CREATE TABLE IF NOT EXISTS `student_affective` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `enroll_id` int(11) NOT NULL,
  `exam_id` int(11) NOT NULL,
  `domain_type_id` int(11) NOT NULL,
  `rating` tinyint(4) NOT NULL DEFAULT 0 COMMENT '1=Poor 2=Fair 3=Good 4=Excellent',
  `branch_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_student_affective` (`enroll_id`,`exam_id`,`domain_type_id`),
  KEY `idx_sa_exam` (`exam_id`,`enroll_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
CREATE TABLE IF NOT EXISTS `student_psychomotor` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `enroll_id` int(11) NOT NULL,
  `exam_id` int(11) NOT NULL,
  `domain_type_id` int(11) NOT NULL,
  `rating` tinyint(4) NOT NULL DEFAULT 0 COMMENT '1=Poor 2=Fair 3=Good 4=Excellent',
  `branch_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_student_psychomotor` (`enroll_id`,`exam_id`,`domain_type_id`),
  KEY `idx_sp_exam` (`exam_id`,`enroll_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
CREATE TABLE IF NOT EXISTS `authorized_pickup_person` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `student_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `relationship` varchar(100) DEFAULT NULL,
  `phone` varchar(50) DEFAULT NULL,
  `id_number` varchar(100) DEFAULT NULL,
  `qr_token` varchar(64) DEFAULT NULL,
  `branch_id` int(11) NOT NULL,
  `is_active` tinyint(1) NOT NULL DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_qr_token` (`qr_token`),
  KEY `idx_student_id` (`student_id`),
  KEY `idx_branch_id` (`branch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE IF NOT EXISTS `pickup_record` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pickup_person_id` int(11) NOT NULL,
  `student_id` int(11) NOT NULL,
  `pickup_date` date NOT NULL,
  `pickup_time` time NOT NULL,
  `scanned_by` int(11) DEFAULT NULL,
  `notes` text DEFAULT NULL,
  `branch_id` int(11) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_pickup_person` (`pickup_person_id`),
  KEY `idx_pickup_student` (`student_id`),
  KEY `idx_pickup_date` (`pickup_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE IF NOT EXISTS `qr_attendance_sessions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `branch_id` int(11) NOT NULL,
  `class_id` int(11) NOT NULL,
  `section_id` int(11) NOT NULL,
  `date` date NOT NULL,
  `opened_by` int(11) DEFAULT NULL,
  `window_open` datetime NOT NULL,
  `window_close` datetime NOT NULL,
  `status` varchar(16) NOT NULL DEFAULT 'open',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_session_lookup` (`branch_id`,`class_id`,`section_id`,`status`),
  KEY `idx_session_window` (`window_open`,`window_close`),
  KEY `idx_session_date` (`branch_id`,`class_id`,`section_id`,`date`,`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE IF NOT EXISTS `mark_audit` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `mark_id` int(11) DEFAULT NULL,
  `student_id` int(11) NOT NULL,
  `subject_id` int(11) NOT NULL,
  `exam_id` int(11) NOT NULL,
  `class_id` int(11) NOT NULL,
  `section_id` int(11) NOT NULL,
  `session_id` int(11) NOT NULL,
  `branch_id` int(11) NOT NULL,
  `action` enum('INSERT','UPDATE','DELETE') NOT NULL,
  `old_mark` text DEFAULT NULL,
  `new_mark` text DEFAULT NULL,
  `old_absent` varchar(4) DEFAULT NULL,
  `new_absent` varchar(4) DEFAULT NULL,
  `changed_by` int(11) NOT NULL COMMENT 'login_credential.id',
  `changed_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_mark_audit_exam` (`exam_id`,`student_id`),
  KEY `idx_mark_audit_changed_by` (`changed_by`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
CREATE TABLE IF NOT EXISTS `sms_queue` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `mobile` varchar(20) NOT NULL,
  `message` text NOT NULL,
  `dlt_template_id` varchar(50) DEFAULT '',
  `branch_id` int(11) NOT NULL,
  `status` tinyint(4) NOT NULL DEFAULT 0 COMMENT '0=pending 1=sent 2=failed',
  `retry_count` tinyint(4) NOT NULL DEFAULT 0,
  `sent_at` datetime DEFAULT NULL,
  `error_msg` varchar(500) DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`,`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE IF NOT EXISTS `term_dates` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `branch_id` int(11) NOT NULL,
  `session_id` int(11) NOT NULL,
  `term` enum('1ST','2ND','3RD') NOT NULL,
  `resumption_date` date NOT NULL,
  `midterm_date` date DEFAULT NULL,
  `exam_start_date` date DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `branch_session_term` (`branch_id`,`session_id`,`term`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE IF NOT EXISTS `subject_rank` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `exam_id` int(11) NOT NULL,
  `enroll_id` int(11) NOT NULL,
  `subject_id` int(11) NOT NULL,
  `rank` int(11) NOT NULL DEFAULT 0,
  `total_marks` decimal(10,2) DEFAULT NULL,
  `branch_id` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_subject_rank` (`exam_id`,`enroll_id`,`subject_id`),
  KEY `idx_sr_exam_subject` (`exam_id`,`subject_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
CREATE TABLE IF NOT EXISTS `parent_wallet` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_id` int(11) NOT NULL,
  `email_address` varchar(200) NOT NULL,
  `payment_gateway` varchar(50) NOT NULL DEFAULT 'paystack',
  `payment_gateway_reference` varchar(1500) NOT NULL DEFAULT '',
  `payment_channel` varchar(30) NOT NULL DEFAULT 'dedicated_nuban',
  `amount` decimal(18,2) NOT NULL DEFAULT 0.00,
  `created_at` datetime NOT NULL DEFAULT current_timestamp(),
  `updated_at` datetime NOT NULL DEFAULT current_timestamp(),
  `update_count` int(11) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_parent_wallet_email` (`email_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
CREATE TABLE IF NOT EXISTS `fee_report_schedules` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `branch_id` int(11) NOT NULL,
  `session_id` int(11) NOT NULL DEFAULT 0,
  `term` varchar(20) NOT NULL DEFAULT '',
  `include_prev_due` tinyint(1) NOT NULL DEFAULT 0,
  `day_of_week` tinyint(1) NOT NULL DEFAULT 1 COMMENT '0=Sun 1=Mon ... 6=Sat',
  `recipients_email` text DEFAULT NULL,
  `recipients_wa` text DEFAULT NULL,
  `active` tinyint(1) NOT NULL DEFAULT 1,
  `last_sent_at` datetime DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_branch` (`branch_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE IF NOT EXISTS `financial_exceptions` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `branch_id` int(11) NOT NULL,
  `exception_type` varchar(50) NOT NULL,
  `severity` enum('critical','warning','info') NOT NULL DEFAULT 'warning',
  `student_id` int(11) DEFAULT NULL,
  `allocation_id` int(11) DEFAULT NULL,
  `amount` decimal(18,2) DEFAULT NULL,
  `description` text NOT NULL,
  `detected_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `resolved` tinyint(1) NOT NULL DEFAULT 0,
  `resolved_at` datetime DEFAULT NULL,
  `resolved_by` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_fe_branch` (`branch_id`),
  KEY `idx_fe_student` (`student_id`),
  KEY `idx_fe_type` (`exception_type`),
  KEY `idx_fe_resolved` (`resolved`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- ---------------------------------------------------------------------------
-- SECTION 2 — Columns absent from production (32)
--
-- Three of these fix features that fail outright without them:
--   exam_attendance.created_by / updated_by  -> exam attendance entry
--   student_attendance.capture_method        -> QR scan + duplicate guard
-- (the third, qr_attendance_sessions, is a table in Section 1)
-- ---------------------------------------------------------------------------

ALTER TABLE `branch` ADD COLUMN IF NOT EXISTS `attendance_threshold` tinyint(3) unsigned NOT NULL DEFAULT 75;
ALTER TABLE `branch` ADD COLUMN IF NOT EXISTS `attendance_backdate_days` tinyint(3) unsigned NOT NULL DEFAULT 7;
ALTER TABLE `branch` ADD COLUMN IF NOT EXISTS `attendance_type` tinyint(4) NOT NULL DEFAULT 0;
ALTER TABLE `exam` ADD COLUMN IF NOT EXISTS `mark_locked` tinyint(1) NOT NULL DEFAULT 0;
ALTER TABLE `exam_attendance` ADD COLUMN IF NOT EXISTS `created_by` int(11) NULL DEFAULT NULL;
ALTER TABLE `exam_attendance` ADD COLUMN IF NOT EXISTS `updated_by` int(11) NULL DEFAULT NULL;
ALTER TABLE `exam_rank` ADD COLUMN IF NOT EXISTS `total_marks` decimal(10,2) NULL DEFAULT NULL;
ALTER TABLE `exam_rank` ADD COLUMN IF NOT EXISTS `total_students` int(11) NULL DEFAULT NULL;
ALTER TABLE `exam_term` ADD COLUMN IF NOT EXISTS `term_start_date` date NULL DEFAULT NULL;
ALTER TABLE `exam_term` ADD COLUMN IF NOT EXISTS `term_end_date` date NULL DEFAULT NULL;
ALTER TABLE `exam_term` ADD COLUMN IF NOT EXISTS `resumption_date` date NULL DEFAULT NULL;
ALTER TABLE `exam_term` ADD COLUMN IF NOT EXISTS `next_term_info` text NULL DEFAULT NULL;
ALTER TABLE `fee_payment_history` ADD COLUMN IF NOT EXISTS `receipt_no` varchar(20) NULL DEFAULT NULL;
ALTER TABLE `fee_payment_history` ADD COLUMN IF NOT EXISTS `gateway_reference` varchar(200) NULL DEFAULT NULL;
ALTER TABLE `fee_payment_history` ADD COLUMN IF NOT EXISTS `status` enum('paid','reversed') NOT NULL DEFAULT 'paid';
ALTER TABLE `fee_payment_history` ADD COLUMN IF NOT EXISTS `reversed_at` datetime NULL DEFAULT NULL;
ALTER TABLE `fee_payment_history` ADD COLUMN IF NOT EXISTS `reversed_by` int(11) NULL DEFAULT NULL;
ALTER TABLE `fee_payment_history` ADD COLUMN IF NOT EXISTS `reversal_reason` varchar(500) NULL DEFAULT NULL;
ALTER TABLE `sms_template_details` ADD COLUMN IF NOT EXISTS `notify_whatsapp` tinyint(3) NOT NULL DEFAULT 0;
ALTER TABLE `staff_attendance` ADD COLUMN IF NOT EXISTS `created_at` timestamp NOT NULL DEFAULT current_timestamp();
ALTER TABLE `staff_attendance` ADD COLUMN IF NOT EXISTS `updated_at` datetime NULL DEFAULT NULL;
ALTER TABLE `staff_attendance` ADD COLUMN IF NOT EXISTS `created_by` int(11) NULL DEFAULT NULL;
ALTER TABLE `staff_attendance` ADD COLUMN IF NOT EXISTS `updated_by` int(11) NULL DEFAULT NULL;
ALTER TABLE `student` ADD COLUMN IF NOT EXISTS `qr_token` varchar(128) NULL DEFAULT NULL;
ALTER TABLE `student` ADD COLUMN IF NOT EXISTS `fees_active` tinyint(1) NOT NULL DEFAULT 1;
ALTER TABLE `student` ADD COLUMN IF NOT EXISTS `fees_deactivated_at` datetime NULL DEFAULT NULL;
ALTER TABLE `student` ADD COLUMN IF NOT EXISTS `fees_deactivated_by` int(11) NULL DEFAULT NULL;
ALTER TABLE `student` ADD COLUMN IF NOT EXISTS `fees_deactivated_reason` varchar(500) NULL DEFAULT NULL;
ALTER TABLE `student_attendance` ADD COLUMN IF NOT EXISTS `period_id` int(11) NULL DEFAULT NULL;
ALTER TABLE `student_attendance` ADD COLUMN IF NOT EXISTS `created_by` int(11) NULL DEFAULT NULL;
ALTER TABLE `student_attendance` ADD COLUMN IF NOT EXISTS `updated_by` int(11) NULL DEFAULT NULL;
ALTER TABLE `student_attendance` ADD COLUMN IF NOT EXISTS `capture_method` varchar(16) NULL DEFAULT NULL;

-- ---------------------------------------------------------------------------
-- SECTION 3 — OPTIONAL: money columns stored as float
--
-- Production stores these as float(10,2); local uses decimal(10,2). float is
-- binary floating point and cannot represent every 2-decimal value exactly,
-- so sums of many payments can drift by small amounts. decimal is exact.
--
-- NOT included above because, unlike everything else here, this REWRITES the
-- column and briefly locks the table. Run it separately, during the
-- maintenance window, after backing up. Values themselves are preserved.
--
-- ALTER TABLE `offline_fees_payments` MODIFY `amount` decimal(10,2) NOT NULL DEFAULT 0.00;
-- ALTER TABLE `offline_fees_payments` MODIFY `fine`   decimal(10,2) NOT NULL DEFAULT 0.00;
-- ---------------------------------------------------------------------------


-- ---------------------------------------------------------------------------
-- SECTION 4 — promotion_history.is_leave
--
-- Student_promotion::transfersave() sets 'is_leave' on every promotion_history
-- row (1 when the student is marked Leave / Add Alumni, 0 otherwise), but the
-- column exists in no deployment, so the insert failed and the whole promotion
-- returned a 500. Existing rows predate the flag and are all ordinary
-- promotions, so 0 is the correct backfill.
-- ---------------------------------------------------------------------------

ALTER TABLE `promotion_history`
  ADD COLUMN IF NOT EXISTS `is_leave` TINYINT(1) NOT NULL DEFAULT 0;
